#!/usr/bin/env python3
"""Turns the overnight CO2 export into shared/night-data.typ (booklet B3).

Input is a Home Assistant history export of a 5-minute-average NDIR CO2
sensor in one bedroom: `entity_id,state,last_changed`, timestamps in UTC.

Three transformations are applied, all of them recorded here so the graph
stays auditable:

1. Meter offset. The meter reads about 100 ppm low (user, 2026-09-21).
   Every value is raised by OFFSET_PPM, so the graph shows CO2 as it
   actually was, not as the meter displayed it. The ventilation automation
   ran off the *uncorrected* reading, which is why its thresholds are 850
   and 700 on the meter but 950 and 800 in the corrected graph.

2. Clock. The export is UTC; the house is in Amsterdam (UTC+2 in
   September). For the booklet the whole night is then moved back four
   hours, so it reads as a normal one: into the bedroom at 21:30 instead of
   01:30. Net: displayed clock = UTC - 2 h (SHIFT_HOURS).

3. Axis. The booklet graph carries no clock times at all; the x-axis is
   hours since the person came into the room (ANCHOR). So the shift above
   has no visible effect. It is kept because the displayed clock times are
   written into the output as a comment, in case a clock-time axis is ever
   wanted back.

Run from the repository root:

    ./tools/make-night-data.py [sources/night-2026-09-16.csv]
"""

import csv
import datetime as dt
import pathlib
import sys

OFFSET_PPM = 100
SHIFT_HOURS = -2
ANCHOR = dt.datetime(2026, 9, 16, 23, 30, tzinfo=dt.timezone.utc)
WINDOW = (
    dt.datetime(2026, 9, 16, 22, 0, tzinfo=dt.timezone.utc),
    dt.datetime(2026, 9, 17, 12, 0, tzinfo=dt.timezone.utc),
)

# The events the resident reported, as UTC instants.
EVENTS = [
    ("enter", dt.datetime(2026, 9, 16, 23, 30, tzinfo=dt.timezone.utc)),
    ("asleep", dt.datetime(2026, 9, 17, 1, 0, tzinfo=dt.timezone.utc)),
    ("vent-up", dt.datetime(2026, 9, 17, 6, 40, tzinfo=dt.timezone.utc)),
    ("leave", dt.datetime(2026, 9, 17, 9, 15, tzinfo=dt.timezone.utc)),
]

# Where the automation switched the fan back down is not read off the clock
# but off the series itself: the first moment the corrected curve comes back
# through VENT_DOWN, interpolated between the two samples that straddle it.
# Taking it from the data is what keeps the shaded strip in the graph and the
# two threshold lines telling the same story -- the strip begins where the
# curve touches 950 and ends where it is back to 800.
#
# That crossing lands at 07:23Z = 09:23 local, on the low point of the dip
# and within the "around 09:30" the resident reported.
VENT_UP = 850 + OFFSET_PPM
VENT_DOWN = 700 + OFFSET_PPM

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "shared" / "night-data.typ"


def hours(when):
    return (when - ANCHOR).total_seconds() / 3600


def read(path):
    rows = []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            try:
                ppm = float(row["state"])
            except ValueError:
                continue  # "unavailable", "unknown"
            when = dt.datetime.fromisoformat(row["last_changed"].replace("Z", "+00:00"))
            rows.append((when, ppm))
    rows.sort()
    return rows


def main():
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "sources" / "night-2026-09-16.csv"
    rows = [(w, p) for (w, p) in read(src) if WINDOW[0] <= w <= WINDOW[1]]
    if not rows:
        sys.exit(f"no samples inside {WINDOW[0]}..{WINDOW[1]} in {src}")

    # Round to whole minutes: the export jitters by a fraction of a second.
    samples = [(round(hours(w) * 60) / 60, p + OFFSET_PPM) for (w, p) in rows]
    lo = min(p for (_, p) in samples)
    hi = max(p for (_, p) in samples)

    # The fall back through VENT_DOWN, in hours, interpolated.
    up_h = hours(dict(EVENTS)["vent-up"])
    down_h = None
    prev = None
    for h, ppm in samples:
        if h > up_h and prev is not None and prev[1] > VENT_DOWN >= ppm:
            span = prev[1] - ppm
            down_h = prev[0] + (h - prev[0]) * (prev[1] - VENT_DOWN) / span
            break
        prev = (h, ppm)
    if down_h is None:
        sys.exit(f"the curve never comes back through {VENT_DOWN} ppm after the step up")

    def clock(when):
        return (when + dt.timedelta(hours=SHIFT_HOURS)).strftime("%H:%M")

    out = [
        "// GENERATED by tools/make-night-data.py -- do not edit by hand.",
        f"// Source: {src.relative_to(ROOT)} ({len(rows)} samples, 5-minute averages).",
        f"// Values are the meter reading + {OFFSET_PPM} ppm: the meter reads that much low.",
        "// x is hours since the resident came into the bedroom.",
        "//",
        "// Events, as displayed clock times (UTC" f"{SHIFT_HOURS:+d}), for reference only:",
    ]
    for name, when in EVENTS:
        out.append(f"//   {clock(when):>5}  h={hours(when):+6.2f}  {name}")
    out.append(f"//   {clock(ANCHOR + dt.timedelta(hours=down_h)):>5}  "
               f"h={down_h:+6.2f}  vent-down (derived from the series)")
    out += [
        "",
        f"#let offset-ppm = {OFFSET_PPM}",
        f"#let x-min = {samples[0][0]:.4f}",
        f"#let x-max = {samples[-1][0]:.4f}",
        f"#let y-observed = ({lo:.1f}, {hi:.1f})",
        "",
        "// Trigger points of the ventilation automation, corrected for the meter",
        "// offset: it runs off the raw reading (850 up, 700 down).",
        f"#let vent-up-ppm = {VENT_UP}",
        f"#let vent-down-ppm = {VENT_DOWN}",
        "",
        "#let events = (",
    ]
    for name, when in EVENTS:
        out.append(f'  "{name}": {hours(when):.4f},')
    out += [
        f'  "vent-down": {down_h:.4f},',
        ")",
        "",
        "// (hours, ppm)",
        "#let samples = (",
    ]
    for h, p in samples:
        out.append(f"  ({h:.4f}, {p:.1f}),")
    out += [")", ""]

    OUT.write_text("\n".join(out))
    print(f"{OUT.relative_to(ROOT)}: {len(samples)} samples, "
          f"{samples[0][0]:+.2f}..{samples[-1][0]:+.2f} h, {lo:.0f}..{hi:.0f} ppm")


if __name__ == "__main__":
    main()
